### ISSUE TITLE
--invert equivalent for pacconf

### ISSUE THREAD

**Issue by AladW** [andrewgregory/pacutils#12]
This could be useful to copy over pacman configuration from an x86_host to an i686 container on an x86_64 host, as the host can set repositories which are invalid for the container (i.e., [multilib] on Arch).

**Comment by andrewgregory** [comment]
Following 92eee4e1c0465a59ceb4a051f84c7596c309448c, this can be done relatively easily with something like the following bash snippet:
```bash
printf "[options]\n"
pacconf --options
while IFS=$'\n' read -r r; do
    printf "[%s]\n" "$r"
    pacconf --repo="$r"
done < <(pacconf --repo-list | grep -vxF -- "$ignored_repo")
```

**Comment by AladW** [comment]
Thanks, that works fine for me.
