### ISSUE TITLE
Typo in paccheck manpage

### ISSUE THREAD

**Issue by pkl97** [andrewgregory/pacutils#17]
paccheck manpage:

**--noextract
Include NoUpgrade files in file modification checks.**

Shouldn't this be "NoExtract" instead of "NoUpgrade"?

**Comment by mkoskar** [comment]
I think so, see #16.

**Comment by andrewgregory** [comment]
Thanks for reporting.  26bf11c2db475179d1192a50a10c6b1a4168b00c
