### ISSUE TITLE
pacreport does not honor /etc/pacreport.conf as advertised

### ISSUE THREAD

**Issue by Edenhofer** [andrewgregory/pacutils#19]
Running `pacreport` with the following config file:
```
[Options]
IgnoreUnowned = home/*
IgnoreUnowned = proc/*
IgnoreUnowned = mnt/*
IgnoreUnowned = /usr/share/icons/*/icon-theme.cache


[PkgIgnoreUnowned]
linux = boot/initramfs-linux.img
linux = boot/initramfs-linux-fallback.img
pacman = /var/lib/pacman/{sync,local}/
systemd = /etc/udev/hwdb.bin
lm_sensors = /etc/conf.d/lm_sensors
upower = /var/lib/upower/history-*.dat
apparmor_profiles = /etc/apparmor.d/cache/
vnstat = /var/lib/vnstat/
netctl = /etc/netctl/*
# Not ideal since this matches old versions as well
#dkms = /usr/lib/modules/*-*/kernel/misc/
```
yields incorrect results: It list the above stated files as unowned though being excepted.

I am using pacutils version 0.4.0 from the official repo and libalpm version 10.0.1 (respectively pacman version 5.0.1).

**Comment by andrewgregory** [comment]
Remove the leading slashes.

**Comment by Edenhofer** [comment]
That was a stupid mistake...
Sorry to have bothered you!

**Comment by andrewgregory** [comment]
No problem; I'll add an explicit note to the documentation before the next release to make it clearer.
