### ISSUE TITLE
paclog doesn't account for +GMT timezones

### ISSUE THREAD

**Issue by glitsj16** [andrewgregory/pacutils#20]
Hi, https://github.com/andrewgregory/pacutils/blob/master/lib/pacutils/util.c#L82 seems to be missing a "+", causing an 'Unable to parse date ...' message in paclog:

$ timedatectl
      Local time: Thu 2017-06-29 06:10:04 CEST
  Universal time: Thu 2017-06-29 04:10:04 UTC
        RTC time: Thu 2017-06-29 04:10:04
       Time zone: Europe/Berlin (CEST, +0200)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no

$ echo "$(date -Iminutes --date '3 days ago')"
2017-06-26T06:10+02:00

$ paclog --after "$(date -Iminutes --date '3 days ago')"
Unable to parse date '2017-06-26T06:11+02:00'

After applying the below patch paclog regains expected behavior.

--- a/lib/pacutils/util.c
+++ b/lib/pacutils/util.c
@@ -79,7 +79,7 @@
   stm->tm_mday = 1;

   /* locate the end of the usable date */
-  if((c = strpbrk(string, " T")) && (c = strpbrk(c, ",.Z-"))) {
+  if((c = strpbrk(string, " T")) && (c = strpbrk(c, ",.Z-+"))) {
     /* ignore trailing timezone and/or fractional elements */
     end = c;
   } else {

I can do a PR if you so desire, regards.

**Comment by andrewgregory** [comment]
Fixed by f2ecde23e2399449582fe0eebf0409b94f3eb05f
