### ISSUE TITLE
pacsift: versioned queries for --satisfies

### ISSUE THREAD

**Issue by AladW** [andrewgregory/pacutils#24]
I'm not sure if it's possible via `libalpm`, but `--satisfies <pkgname>[<cmp><version]` would be useful, for example:
```
pacsift --satisfies=ocaml>=4.02
```

**Comment by andrewgregory** [comment]
Am I missing something? That query already works.

**Comment by eli-schwartz** [comment]
It does work indeed, but not in the way one would expect.

```
$ pacsift --satisfies=ocaml>=4.02
$ cat \=4.02 
local/ocaml
extra/ocaml
```

**Comment by andrewgregory** [comment]
I was giving the benefit of the doubt that the command was being properly quoted.

**Comment by AladW** [comment]
Yeah, I fell into the trap of not properly quoting `>`. Thanks.
