### ISSUE TITLE
pacsift: no output if --sysroot=/ is specified explicitely

### ISSUE THREAD

**Issue by AladW** [andrewgregory/pacutils#26]
Example:
```
$ xargs -a <(printf -- '--satisfies=%s\n' aurutils-git) pacsift --sysroot=/ <&-
# empty output
$ xargs -a <(printf -- '--satisfies=%s\n' aurutils-git) pacsift <&-
local/aurutils-git
alad-base/aurutils-git
```
Note that I'm using `xargs -a` here, because I want to be able to pass many `--satisfies=foo` to `pacsift` without exceeding `ARG_MAX`. I know of no other way to use `--satisfies` with values taken from `stdin`.

**Comment by andrewgregory** [comment]
It's specifically when using --sysroot and <&-.  <&- closes the file descriptor, freeing up fd 0, parsing the config then opens the sysroot directory and gets fd 0, then when pacsift goes to check stdin for packages it sees the directory fd which is not a tty so it tries to read a list of packages, but of course there are none.

**Comment by andrewgregory** [comment]
This should be fixed on the yolo branch.  Can you double check that it works for you?

**Comment by AladW** [comment]
I can confirm it works with latest master. Thanks!
