### ISSUE TITLE
Running `pacreport` without `--group` flag defaults to "{base,base-devel}"

### ISSUE THREAD

**Issue by lucatrv** [andrewgregory/pacutils#35]
As in subject, while IMHO it should default to no groups, in particular now that the "base" group has been replaced with the "base" meta-package:
[https://www.archlinux.org/news/base-group-replaced-by-mandatory-base-package-manual-intervention-required/](https://www.archlinux.org/news/base-group-replaced-by-mandatory-base-package-manual-intervention-required/)

**Comment by andrewgregory** [comment]
Fixed
