### ISSUE TITLE
pacsync $repo and pactrans

### ISSUE THREAD

**Issue by AladW** [andrewgregory/pacutils#4]
pacsync allows syncing a specific repo, while pactrans only allows a general --sysupgrade for all repos. Would it be reasonable to implement a per-repo --sysupgrade for pactrans? 

Example use case: Updating packages from a local (file:///) repository.

**Comment by andrewgregory** [comment]
The ability to sync individual repos follows very naturally from the nature of the tool and the way libalpm handles repo updates.  The same cannot be said for repo-specific sysupgrades.  That would require `pactrans` to skip registering unwanted repos or altering their usage from what is in pacman.conf.  I am not inclined to add that level of granularity to pacutils, at least not at this time.  It could, however, possibly be accomplished by using `pacconf` to build a temporary config file with only the desired repos.  I would need to add an option to get the non-repo settings from `pacconf` but it would look something like: `pactrans --sysupgrade --config=<(printf "[core]\n"; pacconf --repo=core)`

**Comment by andrewgregory** [comment]
92eee4e1c0465a59ceb4a051f84c7596c309448c adds the ability to get just the global options from `pacconf`, making it possible to generate a config file with just the desired repo with something like:
```bash
printf "[options]\n"
pacconf --options
printf "[%s]\n" "$repo"
pacconf --repo="$repo"
```

**Comment by AladW** [comment]
Thanks
