### ISSUE TITLE
pacini: empty output when specifying directives without "-" and stdin input

### ISSUE THREAD

**Issue by AladW** [andrewgregory/pacutils#41]
According to `pacini(1)`:
> If file is omitted or "-" the configuration will be read from stdin.

However, if _file_ is omitted I do not get any output:
```
$ pacconf | pacini --section=custom SigLevel
$ pacconf | pacini --section=custom - SigLevel
PackageOptional
PackageTrustAll
DatabaseOptional
DatabaseTrustAll
```
If no directive is specified, both `-` and leaving out `file` behave the same:
```
$ pacconf --repo=custom | pacini
Usage = All
SigLevel = PackageOptional
SigLevel = PackageTrustAll
SigLevel = DatabaseOptional
SigLevel = DatabaseTrustAll
Server = file:///home/custompkgs

$ pacconf --repo=custom | pacini -
Usage = All
SigLevel = PackageOptional
SigLevel = PackageTrustAll
SigLevel = DatabaseOptional
SigLevel = DatabaseTrustAll
Server = file:///home/custompkgs
```
Version: `pacutils-git 0.10.0.13.gb3cbcbf-1`

**Comment by andrewgregory** [comment]
File is required if a directive is provided, otherwise there's no way to tell a directive from a file name.  The syntax diagram in the man page indicates this correctly, but the --help output needs to be fixed and there should be an error message there.
