### ISSUE TITLE
build 0.11.0 fails

### ISSUE THREAD

**Issue by oberon-manjaro** [andrewgregory/pacutils#44]
On Manjarolinux build of 0.11.0 fails with:

`==> Starting build()...
make -C lib all
make[1]: Entering directory '/build/pacutils/src/pacutils-0.11.0/lib'
cc -DCACHEDIR=\"/var/cache/pacman/pkg\" -DDBEXT=\".db\" -DDBPATH=\"/var/lib/pacman\" -DGPGDIR=\"/etc/pacman.d/gnupg\" -DHOOKDIR=\"/etc/pacman.d/hooks\" -DLOCALSTATEDIR=\"/var\" -DLOGFILE=\"/var/log/pacman.log\" -DROOTDIR=\"/\" -DSYSCONFDIR=\"/etc\" -shared -fPIC -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2,-D_GLIBCXX_ASSERTIONS         -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now  -o libpacutils.so ../ext/globdir.c/globdir.c ../ext/mini.c/mini.c pacutils.c pacutils/config.c pacutils/depends.c pacutils/log.c pacutils/mtree.c pacutils/ui.c pacutils/util.c -lalpm -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
In file included from pacutils.h:39,
                 from pacutils.c:27:
pacutils/ui.h:65:5: error: unknown type name ‘alpm_download_event_type_t’; did you mean ‘alpm_event_type_t’?
   65 |     alpm_download_event_type_t event, void *data);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |     alpm_event_type_t
pacutils.c: In function ‘pu_fetch_pkgurl’:
pacutils.c:75:33: warning: passing argument 2 of ‘alpm_fetch_pkgurl’ from incompatible pointer type [-Wincompatible-pointer-types]
   75 |   if (alpm_fetch_pkgurl(handle, &l, &result) == 0 && result) {
      |                                 ^~
      |                                 |
      |                                 alpm_list_t *
In file included from pacutils.h:33,
                 from pacutils.c:27:
/usr/include/alpm.h:724:60: note: expected ‘const char *’ but argument is of type ‘alpm_list_t *’
  724 | char *alpm_fetch_pkgurl(alpm_handle_t *handle, const char *url);
      |                                                ~~~~~~~~~~~~^~~
pacutils.c:75:7: error: too many arguments to function ‘alpm_fetch_pkgurl’
   75 |   if (alpm_fetch_pkgurl(handle, &l, &result) == 0 && result) {
      |       ^~~~~~~~~~~~~~~~~
In file included from pacutils.h:33,
                 from pacutils.c:27:
/usr/include/alpm.h:724:7: note: declared here
  724 | char *alpm_fetch_pkgurl(alpm_handle_t *handle, const char *url);
      |       ^~~~~~~~~~~~~~~~~
pacutils/config.c: In function ‘pu_initialize_handle_from_config’:
pacutils/config.c:360:3: warning: implicit declaration of function ‘alpm_option_set_architectures’; did you mean ‘alpm_option_set_cachedirs’? [-Wimplicit-function-declaration]
  360 |   alpm_option_set_architectures(handle, config->architectures);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |   alpm_option_set_cachedirs
pacutils/config.c:369:3: warning: implicit declaration of function ‘alpm_option_set_parallel_downloads’ [-Wimplicit-function-declaration]
  369 |   alpm_option_set_parallel_downloads(handle, config->paralleldownloads);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from pacutils/ui.c:28:
pacutils/ui.h:65:5: error: unknown type name ‘alpm_download_event_type_t’; did you mean ‘alpm_event_type_t’?
   65 |     alpm_download_event_type_t event, void *data);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |     alpm_event_type_t
pacutils/ui.c: In function ‘pu_ui_cb_event’:
pacutils/ui.c:182:10: error: ‘ALPM_EVENT_PKG_RETRIEVE_START’ undeclared (first use in this function); did you mean ‘ALPM_EVENT_RETRIEVE_START’?
  182 |     case ALPM_EVENT_PKG_RETRIEVE_START:
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |          ALPM_EVENT_RETRIEVE_START
pacutils/ui.c:182:10: note: each undeclared identifier is reported only once for each function it appears in
pacutils/ui.c:198:10: error: ‘ALPM_EVENT_DB_RETRIEVE_DONE’ undeclared (first use in this function); did you mean ‘ALPM_EVENT_RETRIEVE_DONE’?
  198 |     case ALPM_EVENT_DB_RETRIEVE_DONE:
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |          ALPM_EVENT_RETRIEVE_DONE
pacutils/ui.c:199:10: error: ‘ALPM_EVENT_DB_RETRIEVE_FAILED’ undeclared (first use in this function); did you mean ‘ALPM_EVENT_RETRIEVE_FAILED’?
  199 |     case ALPM_EVENT_DB_RETRIEVE_FAILED:
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |          ALPM_EVENT_RETRIEVE_FAILED
pacutils/ui.c:200:10: error: ‘ALPM_EVENT_DB_RETRIEVE_START’ undeclared (first use in this function); did you mean ‘ALPM_EVENT_RETRIEVE_START’?
  200 |     case ALPM_EVENT_DB_RETRIEVE_START:
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |          ALPM_EVENT_RETRIEVE_START
pacutils/ui.c:216:10: error: ‘ALPM_EVENT_PKG_RETRIEVE_DONE’ undeclared (first use in this function); did you mean ‘ALPM_EVENT_RETRIEVE_DONE’?
  216 |     case ALPM_EVENT_PKG_RETRIEVE_DONE:
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |          ALPM_EVENT_RETRIEVE_DONE
pacutils/ui.c:217:10: error: ‘ALPM_EVENT_PKG_RETRIEVE_FAILED’ undeclared (first use in this function); did you mean ‘ALPM_EVENT_RETRIEVE_FAILED’?
  217 |     case ALPM_EVENT_PKG_RETRIEVE_FAILED:
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |          ALPM_EVENT_RETRIEVE_FAILED
pacutils/ui.c: At top level:
pacutils/ui.c:407:5: error: unknown type name ‘alpm_download_event_type_t’; did you mean ‘alpm_event_type_t’?
  407 |     alpm_download_event_type_t event, void *data) {
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |     alpm_event_type_t
make[1]: *** [Makefile:69: libpacutils.so] Error 1
make[1]: Leaving directory '/build/pacutils/src/pacutils-0.11.0/lib'
make: *** [Makefile:4: lib] Error 2
`
Do you have any pointers for me? Thanks.

**Comment by andrewgregory** [comment]
v0.11.0 requires pacman v6

**Comment by oberon-manjaro** [comment]
OK. thank you.
