### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by halfwit** [andrewgregory/pacutils#5]
https://ptpb.pw/qGrZ occurs on build, using https://ptpb.pw/PCze as a PKGBUILD, on Arch Linux with Pacman 5.0.1-2

**Comment by andrewgregory** [comment]
Can you verify that  commit 8fcfbf9 on the `makefile` branch fixes the issue?  Make sure you don't have pacutils installed when you test it, otherwise it will pick up the installed header instead of the one in the repo.
