### ISSUE TITLE
Man page, actual options, and --help are out of sync

### ISSUE THREAD

**Issue by VorpalBlade** [andrewgregory/pacutils#57]
The actual accepted options and what is documented differ sometimes:

* pacreport has `--optional-deps` which is in the man page but not in `--help`
* paclock and paclog is missing `--help` and `--version` from `--help`

There may be more differences, I have not performed an extensive audit.

**Comment by VorpalBlade** [comment]
Another discrepancy (from issue #58):
> The man pages [for pacreport] erroneously document the --cachedir option as --cache-dir.

**Comment by andrewgregory** [comment]
Fixed
