### ISSUE TITLE
Add .files support for pacsync

### ISSUE THREAD

**Issue by AladW** [andrewgregory/pacutils#60]
The command
```
pacsync myrepo
```
allows to retrieve `.db` files for a given repo, but it does not retrieve `.files`. Since `pacman -Fy` (like `pacman -Sy`) applies to all repositories only, it seems useful for `pacsync` to also support this.

Alternatively, a new command could be added which operates on `.files` databases (like `pacman -F`).

**Comment by andrewgregory** [comment]
--dbext=.files ?

**Comment by AladW** [comment]
Good point!
