### ISSUE TITLE
pacreport can't find pacreport.conf/wrong PREFIX used in PKGBUILD

### ISSUE THREAD

**Issue by drvink** [andrewgregory/pacutils#7]
If you build pacutils-git from the AUR and try to run pacreport, it fails to find pacreport.conf because the build PREFIX is set to /usr/local rather than /usr. I've fixed the makefiles (see PR #6), but you'll also need to fix the PKGBUILD on the AUR. The fix is simple: in the `build()` function, just change `make SYSCONFDIR=/etc LOCALSTATEDIR=/var` to `make PREFIX=/usr SYSCONFDIR=/etc LOCALSTATEDIR=/var`. It looks like this was what you intended to do anyway; just needed to add a few more things to get the preprocessor `#define`s passed through.

**Comment by andrewgregory** [comment]
At build time, `PREFIX` is only used to set defaults for `SYSCONFDIR` and `LOCALSTATEDIR`, so PR #6 should be enough.
