### ISSUE TITLE
pacreport: Appears to ignore the --unowned-files option, outputs everything

### ISSUE THREAD

**Issue by couladin** [andrewgregory/pacutils#72]
Hello!

I'm using 0.11.1-2 on EndeavourOS. Can't see any related changes in the v0.12.0 tag commits.

If I have /etc/pacreport.conf configured (or use the example in the pacreport.1 man page) and run...

    sudo pacreport --unowned-files

...am I correct in thinking that it should _only_ output the "Unowned Files:" section? If so, I think there may be a bug.

In practice, what happens is that the command outputs 6 sections and hundreds of lines:

    Unowned Files:
      ...
    Unneeded Packages Installed Explicitly:
      ...
    Unneeded Packages Installed As Dependencies:
      ...
    Unneeded Packages In A Dependency Cycle:
      ...
    Installed Packages Not In A Repository:
      ...
    Package Cache Size:
      ...

I work around this by piping the output through `awk '/Unneeded Packages Installed Explicitly:/{exit} {print}'` to get what I'm after, but the program does a lot of unnecessary effort and takes a while.

If I have misunderstood, feel free to close this out. Thanks.

**Comment by andrewgregory** [comment]
That is the expected behavior. That option only exists because finding unowned files is expensive and can produce extremely verbose output, so it's disabled by default.
