### ISSUE TITLE
`pacconf` does not recognize `CacheServer` option

### ISSUE THREAD

**Issue by Seas0** [andrewgregory/pacutils#74]
`pacconf --options` complains about `CacheServer` found in `pacman.conf` and `mirrorlist`.
```
warning: config /etc/pacman.d/mirrorlist line 11: unknown option 'CacheServer'
...
RootDir = /
DBPath = /var/lib/pacman
CacheDir = /var/cache/pacman/pkg
...
```
The [CacheServer](https://man.archlinux.org/man/pacman.conf.5.en#:~:text=glob(7)%20rules.-,CacheServer%20%3D%20url,-A%20full%20URL) option was [merged](https://gitlab.archlinux.org/pacman/pacman/-/merge_requests/98) and [released](https://gitlab.archlinux.org/pacman/pacman/-/releases/v6.1.0) in pacman 6.1

**Comment by Seas0** [comment]
Seems #73 already proposed a fix for this issue, waiting for review and merging.

**Comment by HarHarLinks** [comment]
any reason the pacman 6.1 fix #69 has not yet been integrated into a patch release? it is part of the upstream package https://gitlab.archlinux.org/archlinux/packaging/packages/pacutils/-/blob/3eb67f2efad3ff31000cb58cd775b5e9d776ab53/PKGBUILD#L24-26 and apparently working...

**Comment by andrewgregory** [comment]
I have already pushed a release tag with all of the fixes. I am not in charge of Arch's package.

**Comment by HarHarLinks** [comment]
ah, I see, the required fixes were not merged from the branch, but rebased onto master or similar and are thus in v0.13.0 (except) 7fb47bd53bfbb9f727ae88d052c339b6320b63f5. so it's now up to the arch packager to update to v0.14.0.
