### ISSUE TITLE
pacsift --repo misses packages compared to pacman -Sl

### ISSUE THREAD

**Issue by AladW** [andrewgregory/pacutils#9]
pacman.conf: https://ptpb.pw/Z3oc
include file: https://ptpb.pw/htKj

% pacsift --repo=custom | wc -l
241
% pacman -Slq custom | wc -l
278

Missing packages: https://ptpb.pw/sKrS
pacman strace: https://ptpb.pw/3DMr
pacsift strace: https://ptpb.pw/CX9x
database: https://ptpb.pw/u3fb

**Comment by andrewgregory** [comment]
The shaman-git package is the problem; libarchive cannot parse the `α` in its version without having the locale set, so it and anything after it gets silently dropped.  Any program that doesn't set locale (expac for instance) simply won't see any of the packages on your list.  I'm tempted to call this a libalpm bug or packaging error.

**Comment by kyrias** [comment]
I don't really think it's libalpm's job to set the locale, feels like something that's up to the program using it.

**Comment by andrewgregory** [comment]
Correct, but it should be able to parse its databases regardless of the current locale.

**Comment by kyrias** [comment]
Good point.  I guess libalpm would have to read it in as binary data instead of trying to parse it using the current locale, since currently anything that isn't colons or hyphens are fair game in pkgvers.  Though I wonder if it would be reasonable to have a UTF-8 locale as a requirement, hmm...

**Comment by andrewgregory** [comment]
pacsift is definitely not the right place to fix this; any alpm frontend will miss those packages when running under the C locale, including pacman.  libalpm needs to be updated to either be able to read the database regardless of the locale or at least throw an error if that's not possible.  I tried to replicate the error via pacman's test suite and was unable to, so it may also have something to do with how the db was created.  Please open a bug report against pacman, and, if you used something other than repo-add to build the db, maybe poke them too.
